version: "3.8"
services:
  react-app:
    image: pierreverbe/vrac-tool-center-ui:0.1.0-SNAPSHOT
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - vrac-tool-center
  api-server:
    image: pierreverbe/vrac-tool-center-rest-service:0.1.4-SNAPSHOT
    ports:
      - "5000:5000"
    networks:
      - vrac-tool-center
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0.1-focal
    ports:
      - "27017:27017"
    networks:
      - vrac-tool-center
    volumes:
      - mongo-data:/data/db
networks:
  vrac-tool-center:
    driver: bridge
volumes:
  mongo-data:
    driver: local
